# Generated by Django 5.0.1 on 2024-03-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carsinventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarsInventory',
            new_name='CarInventory',
        ),
    ]
